//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.16 at 04:29:26 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.afcpef.fr/produit", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.afcpef.produit;
