//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.17 at 12:42:36 PM CEST 
//


package fr.afcepf.produit;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.afcepf.produit package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Produit_QNAME = new QName("http://www.afcepf.fr/produit", "produit");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.afcepf.produit
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProdType }
     * 
     */
    public ProdType createProdType() {
        return new ProdType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.afcepf.fr/produit", name = "produit")
    public JAXBElement<ProdType> createProduit(ProdType value) {
        return new JAXBElement<ProdType>(_Produit_QNAME, ProdType.class, null, value);
    }

}
